Resources:
  WebSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebSiteBucket
                - /*
      Bucket: !Ref WebSiteBucket
  CF01APIImageRepository: 
    Type: AWS::ECR::Repository
    Properties: 
        RepositoryName: "cf01-api-service"
        RepositoryPolicyText: 
            Version: "2012-10-17"
            Statement: 
              - Sid: AllowPushPull
                Effect: Allow
                Principal: 
                    AWS: 
                    - "arn:aws:iam::380095960694:user/andre"
                Action: 
                    - "ecr:GetDownloadUrlForLayer"
                    - "ecr:BatchGetImage"
                    - "ecr:BatchCheckLayerAvailability"
                    - "ecr:PutImage"
                    - "ecr:InitiateLayerUpload"
                    - "ecr:UploadLayerPart"
                    - "ecr:CompleteLayerUpload"
                    - "ecr:GetAuthorizationToken"
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - WebSiteBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - WebSiteBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
  DockerRegistryURL:
    Value: !GetAtt
      - CF01APIImageRepository
      - RepositoryUri
  