name: Infra

on:
  push:
    branches: [ "infra" ]
  pull_request:
    branches: [ "infra" ]

env:
  AWS_REGION: us-west-2

jobs:
  
  infra-update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::380095960694:role/GithubActionsAssumeRole
          role-session-name: githubactions-cf01-infra-update
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Update infra by cloudformation
        run: aws cloudformation update-stack --stack-name cf01 --template-body file://`pwd`/aws/cloudformation-template.yml
